all:
	python tp.py < tests/1.in > result/1.svg
	python tp.py < tests/2.in > result/2.svg
	python tp.py < tests/3.in > result/3.svg
	python tp.py < tests/4.in > result/4.svg
	python tp.py < tests/5.in > result/5.svg
	python tp.py < tests/6.in > result/6.svg
	python tp.py < tests/7.in > result/7.svg
	python tp.py < tests/8.in > result/8.svg
	python tp.py < tests/9.in > result/9.svg
	python tp.py < tests/10.in > result/10.svg
	python tp.py < tests/11.in > result/11.svg
	python tp.py < tests/12.in > result/12.svg
	python tp.py < tests/13.in > result/13.svg
	python tp.py < tests/14.in > result/14.svg
	python tp.py < tests/15.in > result/15.svg
	python tp.py < tests/16.in > result/16.svg
	python tp.py < tests/17.in > result/17.svg
	python tp.py < tests/18.in > result/18.svg
	python tp.py < tests/19.in > result/19.svg
	python tp.py < tests/20.in > result/20.svg

